### ISSUE TITLE
State labels dataset

### ISSUE THREAD

**Issue by dereklieu** [anandthakker/us-atlas#25]
I was working on including state abbreviations in addition to the state postal, but [this download line](https://github.com/developmentseed/wapo-map-data/blob/master/Makefile#L999) now returns not found. 

@DylanMoriarty can you point me to the right state labels dataset file? Seems like there's 2 on the devseed account and I'm not sure which one is the right one to use (and can we delete the duplicate if it serves no purpose?)

cc @anandthakker

**Comment by DylanMoriarty** [comment]
The link that download line is pointing to, `devseed-cis7wq7mj04l92zpk9tbk9wgo`, is still around, but it's a dataset ([view it here- you'll need to be logged in the devseed account)](https://www.mapbox.com/studio/datasets/devseed/cis7wq7mj04l92zpk9tbk9wgo/) instead of a tileset.

That dataset needs to be exported as a tileset to be used by Studio. You can [see here](https://www.mapbox.com/studio/datasets/devseed/cir7ui0aj00unghm3095sjuuv/) that the previous iteration pre-reprojection is exported to one.

If it has been working since the reprojection, then I'm not sure why it wouldn't be working now, but it might be related to us hitting a tileset cap. I can look into this more tomorrow, as I was already planning on making a post about tending our Mapbox data garden.

**Comment by dereklieu** [comment]
Ah, thanks for pointing me to that. We only need to use that as a dataset so it's not anything to do with the tileset max, the issue as it turns out was that I hadn't set that particular permission on my access token (d'oh!). 

@DylanMoriarty I do look forward to your post on pruning the mapbox data garden.

**Comment by DylanMoriarty** [comment]
d'oh.

That's rad that you can use datasets as well. Dunno what my issue was yesterday uploading tilesets (was getting error messages for everything including simple geojson's), but apparently there isn't a hard limit on the # either as I initially figured.

Still could use some weeding though.

**Comment by dereklieu** [comment]
I used the [state labels dataset](https://www.mapbox.com/studio/datasets/devseed/cis7wq7mj04l92zpk9tbk9wgo/) that our Makefile currently links to, and it seems they are larger than they should be:

![screen shot 2016-09-08 at 4 08 43 pm](https://cloud.githubusercontent.com/assets/1590802/18365026/e767ba64-75de-11e6-9ca0-024b43b470e6.png)

@anandthakker any idea what I'm missing here? Rest of the tiles look fine.

**Comment by dereklieu** [comment]
Nevermind, disregard, this is my issue again.
